name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (if you're working with Python)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies (for Python)
        run: |
          pip install -r requirements.txt

      - name: Run tests (if applicable)
        run: |
          pytest

      - name: Commit changes (for example: adding changes to `README.md`)
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Automated update"
          git push
